const carData = [{
id:1,
car_img:"HY_1.webp", //차량이미지
// 현대: HY , 기아: KI , 제네시스: GE 
// 한국지엠 : SH , KGM: KG , 르노코리아: LE
// 테슬라: TE , 벤츠: BE , 볼보: VO, 아우디: AU
// 폭스바겐: WA, 렉서스 : LEX, 도요타:TO , 포드:FO
// BYD : BY
// 폴스타 : PO
// (르노,렉서스) (볼보,폭스바겐) 겹쳐서 다르게줌
brand_logo: "HYUNDAI.png",  //로고이미지
// AUDI, BENZ, BMW, BYD, CHEVROLET, FORD, GENESIS, HYUNDAI, KGM, KIA, LEXUS, 
// POLESTAR, RENAULT-KOREA, TESLA, TOYATA, VOLKSWAGEN, VOLVO
brand: "현대",  //제조사 
// 현대,기아,제네시스,한국지엠,KGM,르노코리아,테슬라,벤츠,
// BMW,볼보,아우디,폭스바겐,렉서스,도요타,포드,BYD,폴스타
model: "팰리세이드", // mode_detail에서 앞 단어만
model_detail: "팰리세이드 LX3 하이브리드", //모델명 밖에나와있는 ex) 아반떼 CN7 하이브리드
color:"black", // black, gray , silver , white, red, orange, yellow,
// green, blue, violet, gold  中 택
plate_number: "11호2841",
//성중 11호 nnnn 부터 
model_year: 2023, //연식 2022~2025
seats: 9, // 좌석수 
car_size: "대형", //차량등급 (경형/중형/대형)
					 // -> 준중형/준대형
car_type: "SUV", // 승용, SUV, RV , 화물(6인승 택시같이 카니발, 스타리아같은 차), 화물
fuel_type: "휘발유", //연료 ex)휘발유, 경유, 전기, ~
smoking: false, //흡연유무
drive_license_type: "2종", //면허종류
license_years: 1, //면허최소취득기간 (년)국산차 1 / 수입차 3
driver_min_age: 21, //최소대여나이 국산차 21 / 수입차 23
price_value: 1 , // 현대, 기아 1,
								// 제네시스 1.5
								// 한국지엠, KGM, 르노 1,
								// 테슬라 1.5
								// 벤츠 BMW 아우디 2
								// 볼보 1.5
								// 폭스바겐 1.2
								// 렉서스 1.5
								// 도요타 1.2
								// 포드 1.2
								// BYD 1
								// 폴스타 1.5
	
km_per: '16.7km/L',//휘발/경유/하이브리드 ->  12.3km/L  
                  //전기:km/kWh
location: "인천공항", //지점
location_detail: "인천광역시 중구 공항로 271",  // 상세주소
navigation:true,  //네비
rear_camera:true, //후방카메라
heated_seat:true, //엉따
heated_handle:true, //열선핸들 
bluetooth:true, //블루투스
smart_key:true, //스마트키
sun_loof:false //썬루프
},
{
id:2,
car_img:"HY_1.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "팰리세이드", 
model_detail: "팰리세이드 LX3 하이브리드", 
color:"black", 
plate_number: "31호2221",
model_year: 2022, 
seats: 9, 
car_size: "대형", 
car_type: "SUV", 
fuel_type: "하이브리드",
smoking: false, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '16.7km/L',
location: "서울남부", 
location_detail: "서울특별시 서초구 서초대로 283", 
navigation:true, 
rear_camera:true, 
heated_seat:true, 
heated_handle:true,
bluetooth:true,
smart_key:true, 
sun_loof:false 
},
{
id:3,
car_img:"HY_1.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "팰리세이드", 
model_detail: "팰리세이드 LX3 하이브리드", 
color:"black", 
plate_number: "31호2221",
model_year: 2022, 
seats: 9, 
car_size: "대형", 
car_type: "SUV", 
fuel_type: "하이브리드",
smoking: true, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '16.7km/L',
location: "김포공항", 
location_detail: "서울특별시 강서구 하늘길 38", 
navigation:true, 
rear_camera:true, 
heated_seat:true, 
heated_handle:true,
bluetooth:true,
smart_key:true, 
sun_loof:false 
},
{
id:3,
car_img:"HY_1.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "팰리세이드", 
model_detail: "팰리세이드 LX3 하이브리드", 
color:"black", 
plate_number: "31호2221",
model_year: 2024, 
seats: 9, 
car_size: "대형", 
car_type: "SUV", 
fuel_type: "하이브리드",
smoking: false, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '16.7km/L',
location: "서울남부", 
location_detail: "서울특별시 서초구 서초대로 283", 
navigation:true, 
rear_camera:true, 
heated_seat:true, 
heated_handle:true,
bluetooth:true,
smart_key:true, 
sun_loof:false 
},
{
id:4,
car_img:"HY_1.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "팰리세이드", 
model_detail: "팰리세이드 LX3 하이브리드", 
color:"white", 
plate_number: "30호2700",
model_year: 2025, 
seats: 9, 
car_size: "대형", 
car_type: "SUV", 
fuel_type: "하이브리드",
smoking: false, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '16.7km/L',
location: "서울서부", 
location_detail: "서울특별시 강서구 마곡동로 56", 
navigation:true, 
rear_camera:true, 
heated_seat:true, 
heated_handle:true,
bluetooth:true,
smart_key:true, 
sun_loof:false 
},
{
id:5,
car_img:"HY_1.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "팰리세이드", 
model_detail: "팰리세이드 LX3 하이브리드", 
color:"black", 
plate_number: "43호2320",
model_year: 2023, 
seats: 9, 
car_size: "대형", 
car_type: "SUV", 
fuel_type: "하이브리드",
smoking: false, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '16.7km/L',
location: "서울북부", 
location_detail: "서울 노원구 노해로 456 동방빌딩 1층", 
navigation:true, 
rear_camera:true, 
heated_seat:true, 
heated_handle:true,
bluetooth:true,
smart_key:true, 
sun_loof:false 
},
{
id:6,
car_img:"HY_2.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7 하이브리드", 
color:"black", 
plate_number: "31호2221",
model_year: 2025, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: false, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '18.0km/L',
location: "서울북부", 
location_detail: "서울 노원구 노해로 456 동방빌딩 1층", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:true, 
sun_loof:true 
},
{
id:7,
car_img:"HY_2.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7 하이브리드", 
color:"black", 
plate_number: "16호7650",
model_year: 2024, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: false, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '18.0km/L',
location: "수원", 
location_detail: "경기 수원시 장안구 장안로 73 1층", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:true 
},
{
id:8,
car_img:"HY_2.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7 하이브리드", 
color:"black", 
plate_number: "16호7651",
model_year: 2023, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: false, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '18.0km/L',
location: "성남", 
location_detail: "경기 성남시 분당구 야탑로 64 에이스코아 1층", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:true 
},
{
id:9,
car_img:"HY_2.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7 하이브리드", 
color:"white", 
plate_number: "10호2211",
model_year: 2020, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: false, 
drive_license_type: "2종", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '18.0km/L',
location: "김포공항", 
location_detail: "서울특별시 강서구 하늘길 38", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:true 
},
{
id:10,
car_img:"HY_2.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7 하이브리드", 
color:"white", 
plate_number: "70호4444",
model_year: 2024, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: true, 
drive_license_type: "2종보통", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '18.0km/L',
location: "성남", 
location_detail: "경기 성남시 분당구 야탑로 64 에이스코아 1층", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:false
},
{
id:11,
car_img:"HY_3.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7", 
color:"black", 
plate_number: "70호2888",
model_year: 2024, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: true, 
drive_license_type: "2종보통", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '11.7km/L',
location: "서울남부", 
location_detail: "서울특별시 서초구 서초대로 283", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:false 
},
{
id:12,
car_img:"HY_3.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7", 
color:"white", 
plate_number: "70호2686",
model_year: 2024, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: true, 
drive_license_type: "2종보통", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '11.7km/L',
location: "김포공항", 
location_detail: "서울특별시 강서구 하늘길 38", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:false
},
{
id:13,
car_img:"HY_3.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7", 
color:"black", 
plate_number: "70호2881",
model_year: 2024, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: true, 
drive_license_type: "2종보통", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '11.7km/L',
location: "서울서부", 
location_detail: "서울특별시 강서구 마곡동로 56", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:false
},
{
id:14,
car_img:"HY_3.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7", 
color:"white", 
plate_number: "70호2500",
model_year: 2024, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: true, 
drive_license_type: "2종보통", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '11.7km/L',
location: "서울남부", 
location_detail: "서울특별시 서초구 서초대로 283", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:false
},
{
id:15,
car_img:"HY_3.webp",
brand_logo: "HYUNDAI.png", 
brand: "현대", 
model: "그랜저", 
model_detail: "그랜저 GN7", 
color:"white", 
plate_number: "70호2551",
model_year: 2024, 
seats: 5, 
car_size: "대형", 
car_type: "승용", 
fuel_type: "하이브리드",
smoking: true, 
drive_license_type: "2종보통", 
license_years: 1, 
driver_min_age: 21,
price_value: 1 ,
km_per: '11.7km/L',
location: "서울북부", 
location_detail: "서울 노원구 노해로 456 동방빌딩 1층", 
navigation:true, 
rear_camera:true, 
heated_seat:false, 
heated_handle:true,
bluetooth:true,
smart_key:false, 
sun_loof:false 
},
{
id:16,
car_img: "HY_4.webp",
brand_logo: "HYUNDAI.png",
brand: "현대",
model: "아반떼",
model_detail: "아반떼 CN7",
color: "black",
plate_number: "12호1135",
model_year: 2024,
seats: 5,
car_size: "준중형",
car_type: "승용",
fuel_type: "휘발유",
smoking: false,
drive_license_type: "2종",
license_years: 1,
driver_min_age: 21,
price_value: 1,
km_per: "15.0km/L",
location: "김포공항",
location_detail: "서울특별시 강서구 하늘길 38",
navigation: true,
rear_camera: true,
heated_seat: false,
heated_handle: true,
bluetooth: true,
smart_key: true,
sun_loof: false
},
{
id: 17,
car_img: "HY_4.webp",
brand_logo: "HYUNDAI.png",
brand: "현대",
model: "아반떼",
model_detail: "아반떼 CN7",
color: "black",
plate_number: "52호1212",
model_year: 2024,
seats: 5,
car_size: "준중형",
car_type: "승용",
fuel_type: "휘발유",
smoking: false,
drive_license_type: "2종",
license_years: 1,
driver_min_age: 21,
price_value: 1,
km_per: "15.0km/L",
location: "평택",
location_detail: "경기 평택시 만세로 1709 1층",
navigation: true,
rear_camera: true,
heated_seat: false,
heated_handle: true,
bluetooth: true,
smart_key: true,
sun_loof: false
},
{
id: 18,
car_img: "HY_4.webp",
brand_logo: "HYUNDAI.png",
brand: "현대",
model: "아반떼",
model_detail: "아반떼 CN7",
color: "silver",
plate_number: "10호1203",
model_year: 2024,
seats: 5,
car_size: "준중형",
car_type: "승용",
fuel_type: "휘발유",
smoking: false,
drive_license_type: "2종",
license_years: 1,
driver_min_age: 21,
price_value: 1,
km_per: "15.0km/L",
location: "인천공항",
location_detail: "인천광역시 중구 공항로 271",
navigation: true,
rear_camera: true,
heated_seat: true,
heated_handle: true,
bluetooth: true,
smart_key: true,
sun_loof: false
},
{
id: 19,
car_img: "HY_4.webp",
brand_logo: "HYUNDAI.png",
brand: "현대",
model: "아반떼",
model_detail: "아반떼 CN7",
color: "black",
plate_number: "33호1213",
model_year: 2022,
seats: 5,
car_size: "준중형",
car_type: "승용",
fuel_type: "휘발유",
smoking: true,
drive_license_type: "2종",
license_years: 1,
driver_min_age: 21,
price_value: 1,
km_per: "15.0km/L",
location: "서울남부",
location_detail: "서울특별시 서초구 서초대로 283",
navigation: true,
rear_camera: true,
heated_seat: true,
heated_handle: true,
bluetooth: true,
smart_key: true,
sun_loof: false
},
{
id: 20,
car_img: "HY_4.webp",
brand_logo: "HYUNDAI.png",
brand: "현대",
model: "아반떼",
model_detail: "아반떼 CN7",
color: "gray",
plate_number: "12호1203",
model_year: 2024,
seats: 5,
car_size: "준중형",
car_type: "승용",
fuel_type: "휘발유",
smoking: false,
drive_license_type: "2종",
license_years: 1,
driver_min_age: 21,
price_value: 1,
km_per: "15.0km/L",
location: "서울동부",
location_detail: "서울 동대문구 한천로 100 1-2층",
navigation: true,
rear_camera: true,
heated_seat: true,
heated_handle: true,
bluetooth: true,
smart_key: true,
sun_loof: false
},
]