[
    // 쌍용 - KGB
    {id:244,
    car_img: "KGM_1.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 티볼라",
    color:"white",
    plate_number: "13허0001",
    model_year: 2022,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "휘발유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '12.3km/L',
    location: "서울남부",
    location_detail: "서울특별시 서초구 서초대로 283",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:true,
    smart_key:true,
    sun_loof:false
    },
    {id:245,
    car_img: "KGM_1.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 티볼라",
    color:"white",
    plate_number: "13허0002",
    model_year: 2022,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "하이브리드",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '12.3km/L',
    location: "인천공항",
    location_detail: "서인천광역시 중구 공항로 271",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:false,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:246,
    car_img: "KGM_1.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 티볼라",
    color:"white",
    plate_number: "13허0003",
    model_year: 2022,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "휘발유",
    smoking: true,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '12.3km/L',
    location: "김포공항",
    location_detail: "서울특별시 강서구 하늘길 38",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:false,
    smart_key:false,
    sun_loof:false
    },
    {id:247,
    car_img: "KGM_2.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 레스턴 뉴 아레니",
    color:"black",
    plate_number: "13허0011",
    model_year: 2023,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "경유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '11km/L',
    location: "서울북부",
    location_detail: "서울 노원구 노해로 456 동방빌딩 1층",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:false,
    smart_key:false,
    sun_loof:false
    },
    {id:248,
    car_img: "KGM_2.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 레스턴 뉴 아레니",
    color:"white",
    plate_number: "13허0021",
    model_year: 2023,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "경유",
    smoking: true,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '11km/L',
    location: "서울남부",
    location_detail: "서울특별시 서초구 서초대로 283",
    navigation:false,
    rear_camera:true,
    heated_seat:false,
    heated_handle:true,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:249,
    car_img: "KGM_2.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 레스턴 뉴 아레니",
    color:"black",
    plate_number: "13허0031",
    model_year: 2023,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "하이브리드",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '11km/L',
    location: "김포공항",
    location_detail: "서울특별시 강서구 하늘길 38",
    navigation:true,
    rear_camera:true,
    heated_seat:false,
    heated_handle:false,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:250,
    car_img: "KGM_3.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 에티언(H130)",
    color:"white",
    plate_number: "13허0111",
    model_year: 2025,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "휘발유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '14km/L',
    location: "서울동부",
    location_detail: "서울 동대문구 한천로 100 1-2층",
    navigation:true,
    rear_camera:true,
    heated_seat:false,
    heated_handle:false,
    bluetooth:false,
    smart_key:false,
    sun_loof:false
    },
    {id:251,
    car_img: "KGM_3.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 에티언(H130)",
    color:"white",
    plate_number: "13허0211",
    model_year: 2025,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "경유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '14km/L',
    location: "인천공항",
    location_detail: "인천광역시 중구 공항로 271",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:252,
    car_img: "KGM_3.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 에티언(H130)",
    color:"gray",
    plate_number: "13허0311",
    model_year: 2025,
    seats: 5,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "휘발유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '14km/L',
    location: "김포공항",
    location_detail: "서울특별시 강서구 하늘길 38",
    navigation:true,
    rear_camera:true,
    heated_seat:false,
    heated_handle:true,
    bluetooth:false,
    smart_key:false,
    sun_loof:false
    },
    {id:253,
    car_img: "KGM_4.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 도렉스",
    color:"white",
    plate_number: "13허1111",
    model_year: 2025,
    seats: 6,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "휘발유",
    smoking: true,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '14km/L',
    location: "김포공항",
    location_detail: "서울특별시 강서구 하늘길 38",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:254,
    car_img: "KGM_4.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 도렉스",
    color:"black",
    plate_number: "13허2111",
    model_year: 2025,
    seats: 6,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "경유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '14km/L',
    location: "인천공항",
    location_detail: "인천광역시 중구 공항로 271",
    navigation:true,
    rear_camera:true,
    heated_seat:false,
    heated_handle:true,
    bluetooth:false,
    smart_key:false,
    sun_loof:false
    },
    {id:255,
    car_img: "KGM_4.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 도렉스",
    color:"gray",
    plate_number: "13허3111",
    model_year: 2025,
    seats: 6,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "하이브리드",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '14km/L',
    location: "서울북부",
    location_detail: "서울 노원구 노해로 456 동방빌딩 1층",
    navigation:false,
    rear_camera:false,
    heated_seat:true,
    heated_handle:true,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:256,
    car_img: "KGM_5.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 도뉴",
    color:"white",
    plate_number: "13허4111",
    model_year: 2025,
    seats: 6,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "휘발유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '12.4km/L',
    location: "서울북부",
    location_detail: "서울 노원구 노해로 456 동방빌딩 1층",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:257,
    car_img: "KGM_5.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 도뉴",
    color:"black",
    plate_number: "13허5111",
    model_year: 2025,
    seats: 6,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "경유",
    smoking: true,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '12.4km/L',
    location: "서울북부",
    location_detail: "서울 노원구 노해로 456 동방빌딩 1층",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:258,
    car_img: "KGM_5.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 도뉴",
    color:"white",
    plate_number: "13허6111",
    model_year: 2025,
    seats: 6,
    car_size: "중형",
    car_type: "승용",
    fuel_type: "경유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '12.4km/L',
    location: "서울남부",
    location_detail: "서울특별시 서초구 서초대로 283",
    navigation:false,
    rear_camera:true,
    heated_seat:true,
    heated_handle:false,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:259,
    car_img: "KGM_6.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 무쓰",
    color:"gray",
    plate_number: "13허7111",
    model_year: 2025,
    seats: 4,
    car_size: "중형",
    car_type: "화물",
    fuel_type: "휘발유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '11.5km/L',
    location: "김포공항",
    location_detail: "서울특별시 강서구 하늘길 38",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    {id:260,
    car_img: "KGM_6.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 무쓰",
    color:"yellow",
    plate_number: "13허8111",
    model_year: 2025,
    seats: 4,
    car_size: "중형",
    car_type: "화물",
    fuel_type: "휘발유",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '11.5km/L',
    location: "서울동부",
    location_detail: "서울 동대문구 한천로 100 1-2층",
    navigation:true,
    rear_camera:true,
    heated_seat:false,
    heated_handle:true,
    bluetooth:false,
    smart_key:false,
    sun_loof:false
    },
    {id:261,
    car_img: "KGM_6.webp",
    brand_logo: "KGM.png",
    brand: "KGB",
    model: "KGB 무쓰",
    color:"white",
    plate_number: "13허9111",
    model_year: 2025,
    seats: 4,
    car_size: "중형",
    car_type: "화물",
    fuel_type: "하이브리드",
    smoking: false,
    drive_license_type: "1종",
    license_years: 3,
    driver_min_age: 21,
    price_value: 1,
    km_per: '11.5km/L',
    location: "김포공항",
    location_detail: "서울특별시 강서구 하늘길 38",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:true,
    bluetooth:true,
    smart_key:false,
    sun_loof:false
    },
    // gpt
    {id:263,
    car_img:"KGM_7.webp",
    brand_logo:"KGM.png",
    brand:"KGM",
    model:"KGM 디렉스",
    color:"white",
    plate_number:"18허4023",
    model_year:2024,
    seats:5,
    car_size:"중형",
    car_type:"SUV",
    fuel_type:"경유",
    smoking:false,
    drive_license_type:"1종",
    license_years:3,
    driver_min_age:23,
    price_value:1.5,
    km_per:"11.2km.L",
    location:"서울북부",
    location_detail:"서울 노원구 노해로 456 동방빌딩 1층",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:false,
    bluetooth:true,
    smart_key:true,
    sun_loof:false
    },
    {id:264,
    car_img:"KGM_7.webp",
    brand_logo:"KGM.png",
    brand:"KGM",
    model:"KGM 디렉스",
    color:"black",
    plate_number:"16허9301",
    model_year:2023,
    seats:5,
    car_size:"중형",
    car_type:"SUV",
    fuel_type:"휘발유",
    smoking:false,
    drive_license_type:"1종",
    license_years:3,
    driver_min_age:23,
    price_value:1.5,
    km_per:"12.6km/L",
    location:"인천공항",
    location_detail:"인천광역시 중구 공항로 271",
    navigation:true,
    rear_camera:true,
    heated_seat:false,
    heated_handle:true,
    bluetooth:true,
    smart_key:true,
    sun_loof:false
    },
    {id:265,
    car_img:"KGM_7.webp",
    brand_logo:"KGM.png",
    brand:"KGM",
    model:"KGM 디렉스",
    color:"silver",
    plate_number:"12허5839",
    model_year:2025,
    seats:5,
    car_size:"중형",
    car_type:"SUV",
    fuel_type:"하이브리드",
    smoking:false,
    drive_license_type:"1종",
    license_years:3,
    driver_min_age:23,
    price_value:1.5,
    km_per:"13.1km/L",
    location:"서울동부",
    location_detail:"서울 동대문구 한천로 100 1-2층",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:false,
    bluetooth:false,
    smart_key:false,
    sun_loof:false
    },
    {id:266,
    car_img:"KGM_8.webp",
    brand_logo:"KGM.png",
    brand:"KGM",
    model:"KGM 엘디온",
    color:"gray",
    plate_number:"13허5812",
    model_year:2025,
    seats:5,
    car_size:"중형",
    car_type:"SUV",
    fuel_type:"하이브리드",
    smoking:false,
    drive_license_type:"1종",
    license_years:3,
    driver_min_age:23,
    price_value:1.5,
    km_per:"13.1km/L",
    location:"김포공항",
    location_detail:"서울특별시 강서구 하늘길 38",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:false,
    bluetooth:false,
    smart_key:false,
    sun_loof:false
    },
    {id:267,
    car_img:"KGM_8.webp",
    brand_logo:"KGM.png",
    brand:"KGM",
    model:"KGM 엘디온",
    color:"red",
    plate_number:"13허5813",
    model_year:2025,
    seats:5,
    car_size:"중형",
    car_type:"SUV",
    fuel_type:"하이브리드",
    smoking:false,
    drive_license_type:"1종",
    license_years:3,
    driver_min_age:23,
    price_value:1.5,
    km_per:"13.1km/L",
    location:"서울동부",
    location_detail:"서울 동대문구 한천로 100 1-2층",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:false,
    bluetooth:false,
    smart_key:true,
    sun_loof:false
    },
    {id:268,
    car_img:"KGM_8.webp",
    brand_logo:"KGM.png",
    brand:"KGM",
    model:"KGM 엘디온",
    color:"white",
    plate_number:"13허5815",
    model_year:2025,
    seats:5,
    car_size:"중형",
    car_type:"SUV",
    fuel_type:"하이브리드",
    smoking:true,
    drive_license_type:"1종",
    license_years:3,
    driver_min_age:23,
    price_value:1.5,
    km_per:"13.1km/L",
    location:"인천공항",
    location_detail:"인천광역시 중구 공항로 271",
    navigation:true,
    rear_camera:true,
    heated_seat:true,
    heated_handle:false,
    bluetooth:false,
    smart_key:false,
    sun_loof:true
    },
]